package ca.ualberta.c301w19t14.onebook.models;

import android.support.annotation.NonNull;
import android.util.Log;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.auth.UserProfileChangeRequest;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

/**
 * This class is for the user and encompasses borrowers and owners
 * @author CMPUT301 Team14
 * @see ca.ualberta.c301w19t14.onebook.activities.UserLoginActivity
 * @version 1.0
 */
public class User {

    private String uid;
    private String name;
    private String email;

    /**
     *
     */
    public User() {
    }

    /**
     *
     * @param uid: String
     * @param name: String
     * @param email: String
     */
    public User( String uid, String name, String email){
        this.uid = uid;
        this.name = name;
        this.email = email;
    }

    /**
     * updates the firebase database
     * @param firebaseUid: String
     */
    public static void updateDatabase(final String firebaseUid) {
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference myRef = database.getReference("Users");
        FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
        final User userClass = new User(firebaseUid, user.getDisplayName(), user.getEmail());
        myRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if(!dataSnapshot.child(firebaseUid).exists()) {
                    Notification newUser = new Notification("Welcome to OneBook", "Borrow your first book in seconds. Get started by opening the menu.", userClass, Notification.ROCKET);
                    newUser.save();

                    Notification welcome = new Notification("Using the Camera Button", "At any time, you can click the camera button on the top right to search, borrow or return a book.", userClass, Notification.ROCKET);
                    welcome.save();
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

        Log.e("tag", userClass.getEmail());

        myRef.child(firebaseUid).setValue(userClass);
    }

    /**
     * updates the user's email
     * @param firebaseUid: String
     * @param new_email: String
     */
    public static void updateEmail(final String firebaseUid, final String new_email) {
        FirebaseAuth.getInstance().getCurrentUser().updateEmail(new_email).addOnCompleteListener(new OnCompleteListener<Void>() {
            @Override
            public void onComplete(@NonNull Task<Void> task) {
                updateDatabase(firebaseUid);
            }
        });
    }

    /**
     * updates the user's name
     * @param firebaseUid: String
     * @param new_name: String
     */
    public static void updateName(final String firebaseUid, String new_name) {
        FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
        user.updateProfile(new UserProfileChangeRequest.Builder().setDisplayName(new_name).build());
    }

    /**
     * updates the user's passwords
     * @param firebaseUid: String
     * @param new_password: String
     */
    public static void updatePassword(final String firebaseUid, String new_password) {
        FirebaseAuth.getInstance().getCurrentUser().updatePassword(new_password);
    }

    /**
     * setter email
     * @param email: String
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * getter for user id. user id's are automatically generated by firebase
     * @return uid
     */
    public String getUid(){ return this.uid; }

    /**
     * getter for user name
     * @return name
     */
    public String getName(){ return this.name; }

    /**
     * getter for email
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * set user id
     * @param uid: String
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * set user name
     * @param name: String
     */
    public void setName(String name) {
        this.name = name;
    }
}

